apiVersion: v1
kind: Service
metadata:
  name: kstreams-demo
  annotations:
    ingress.kubernetes.io/service-upstream: 'true'
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kstreams-demo
  type: ClusterIP